services:
  - type: web
    name: affiliate-store
    runtime: node
    buildCommand: npm install && npm run seed
    startCommand: npm start
    envVars:
      - key: SESSION_SECRET
        generateValue: true
